### ISSUE TITLE
Amp V3 version and socks5 proxy request

### ISSUE THREAD

**Issue by xpader** [amphp/http-tunnel#2]
Is there any plan to implement this?
We're unable to migrate to v3 version cause we need http/socks5 proxy support for http-client.

**Comment by kelunik** [comment]
Yes, it'll be updated.

**Comment by kelunik** [comment]
There's now a beta release. Please give this a try!

**Comment by xpader** [comment]
I tested it works fine, there is also a small request, when can socks5 proxy be supported?

**Comment by kelunik** [comment]
I don't have any plans to implement this right now. Please open an issue in the http-tunnel repository and send a PR if you need it.
