### ISSUE TITLE
Using http or socks proxy with username / password authorization

### ISSUE THREAD

**Issue by alexdnepro** [amphp/http-tunnel#3]
I would like to see an example of using this type of proxy. And in general, with the new version of amp, it is extremely difficult to find any examples

**Comment by kelunik** [comment]
You can find examples in the `examples` directory: https://github.com/amphp/http-tunnel/blob/3f8aaa2730c3c0eb1561a33bdb7be231308f5d18/examples/http-client-via-socks5.php
